[MODCLUSTER-758] improve proxy_cluster_post_request locking
modcluster/mod_cluster pull request #609
Opened 2022-07-06 17:38 UTC by aogburn

https://issues.redhat.com/browse/MODCLUSTER-758

2022-07-07 10:42 UTC, rhusar commented
@jfclere Please review. Also, this will probably need a forward-port PR to 2.x.

2022-07-27 14:09 UTC, jfclere requested changes

2022-07-27 14:09 UTC, jfclere commented on native/mod_proxy_cluster/mod_proxy_cluster.c
>          int i;
the int i; needs to be before the if()

2022-07-27 14:32 UTC, jfclere commented
Upstream PR https://github.com/modcluster/mod_proxy_cluster/pull/43

2022-08-03 07:47 UTC, merged