MODCLUSTER-807 Change the mod_cluster license to ASL 2.0
modcluster/mod_cluster pull request #760
Opened 2023-12-05 14:26 UTC by rhusar

Resolves
https://issues.redhat.com/browse/MODCLUSTER-807

2023-12-07 11:16 UTC, jajik requested changes
Other than the http instead of httpS it looks correct.

I left there some comments about inconsistent blank spaces after comments, but that's not an issue.

2023-12-07 11:16 UTC, jajik commented on container/spi/src/main/java/org/jboss/modcluster/container/Connector.java
> +
Is this intentional?

2023-12-07 11:16 UTC, jajik commented on container/tomcat-8.5/src/main/java/org/jboss/modcluster/container/tomcat/mbeans-descriptors.xml
> +
Here again (I mean the blank space – there's no blank line on most places).

2023-12-07 11:16 UTC, jajik commented on container/tomcat-9.0/src/main/java/org/jboss/modcluster/container/tomcat/mbeans-descriptors.xml
> +
Same.

2023-12-07 11:16 UTC, jajik commented on core/src/main/java/org/jboss/modcluster/config/ProxyConfiguration.java
Same.

2023-12-07 11:16 UTC, jajik commented on core/src/main/java/org/jboss/modcluster/config/builder/AbstractConfigurationBuilder.java
Same.

2023-12-07 11:16 UTC, jajik commented on core/src/main/java/org/jboss/modcluster/config/builder/AdvertiseConfigurationBuilder.java
Same

2023-12-07 11:16 UTC, jajik commented on core/src/main/java/org/jboss/modcluster/config/builder/BalancerConfigurationBuilder.java
Same

2023-12-07 11:16 UTC, jajik commented on core/src/main/java/org/jboss/modcluster/config/builder/Creator.java
Same.

2023-12-07 11:31 UTC, rhusar commented on pom.xml
> +            <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
I used the code from wildfly, but I see no reason to use http here either... i will fix this.

[rhusar@ribera tmp]$ curl --head http://repository.jboss.org/licenses/apache-2.0.txt
HTTP/1.1 301 Moved Permanently
Server: AkamaiGHost
Content-Length: 0
Location: https://repository.jboss.org/licenses/apache-2.0.txt
Expires: Thu, 07 Dec 2023 11:30:47 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Thu, 07 Dec 2023 11:30:47 GMT
Connection: keep-alive
x-rh-edge-request-id: 262299b7
x-rh-edge-reference-id: 0.7ef06e68.1701948647.262299b7
x-rh-edge-cache-status: NotCacheable from child

2023-12-07 11:52 UTC, rhusar commented on container/spi/src/main/java/org/jboss/modcluster/container/Connector.java
> +
Not sure how that happened, fixed.

2023-12-07 11:53 UTC, rhusar commented on core/src/main/java/org/jboss/modcluster/config/builder/AdvertiseConfigurationBuilder.java
Let's go with no space after licence - fixed.

2023-12-07 11:53 UTC, rhusar commented on core/src/main/java/org/jboss/modcluster/config/builder/BalancerConfigurationBuilder.java
Let's go with no space after licence - fixed.

2023-12-07 11:53 UTC, rhusar commented on core/src/main/java/org/jboss/modcluster/config/builder/ConfigurationBuilder.java
Let's go with no space after licence - fixed.

2023-12-07 11:53 UTC, rhusar commented on pom.xml
> +            <url>http://repository.jboss.org/licenses/apache-2.0.txt</url>
Fixed.

2023-12-07 12:04 UTC, jajik requested changes

2023-12-07 13:31 UTC, rhusar commented on README.md
> +* [Apache License 2.0](http://www.apache.org/licenses/LICENSE-2.0)
The licence itself references this URL, i.e.

Apache License
Version 2.0, January 2004
http://www.apache.org/licenses/

but I dont think that matters. Lets not be silly and use https  here too.

2023-12-07 13:40 UTC, jajik approved these changes
LGTM

2023-12-10 23:38 UTC, merged

2023-12-10 23:38 UTC, rhusar commented
Thanks for the review @jajik